[2단계] 한석진 미션 제출합니다.
CNU-SPICY/java-racingcar pull request #10
Opened 2024-01-12 09:39 UTC by hsjni0110

# 어려웠던 점

- 테스트 코드 작성 시 mock을 사용하려고 했는데, 생각보다 어렵습니다..ㅜㅜ

- 테스트 코드를 작성하다 보니, 본 코드를 손 봐야 할 때가 있습니다. 이때 객체 지향적인 코드이기 보단, 테스트 코드 작성을 위한 코드가 될 때가 있어 어려움을 겪었습니다.

2024-01-13 12:23 UTC, shin-mallang reviewed
미션 고생하셨습니다 :)
코드 너무 예쁘게 잘 짜주셨네요 👍
간단하게 리뷰 남겼으니 확인 부탁드려요!
리뷰 반영해주실 때, 기본적으로 코드 형식 (공백, Final 등등)은 맞춰주시면 감사하겠습니다!

---
Q. 테스트 코드 작성 시 mock을 사용하려고 했는데, 생각보다 어렵습니다..ㅜㅜ
A. mockito 라이브러리는 사용하지 않았지만, 랜덤 생성기를 테스트용으로 만들어 사용하신 것으로도 충분히 mock(여기서는 test double 이라고 하는게 좋을까요? ㅎㅎ)을 잘 사용해주셨다고 생각합니다

---
Q. 테스트 코드를 작성하다 보니, 본 코드를 손 봐야 할 때가 있습니다. 이때 객체 지향적인 코드이기 보단, 테스트 코드 작성을 위한 코드가 될 때가 있어 어려움을 겪었습니다.
A. 테스트를 위한 코드 작성은 `지양` 하는게 맞겠죠. 이런 저런 방법들을 고민해보며 테스트를 위한 코드 작성을 피할 방법을 계속해서 찾아보는 노력이 필요할 것 같아요.
그런데 테스트를 위한 코드 작성은 `지양`하는게 좋지만, 테스트하기 쉬운 구조로 코드를 작성하는것은 `지향` 하셔야 합니다 ㅎㅎ.
대체로 객체지향적으로 잘 작성된 코드는 테스트하기도 쉬워지는 경향이 있어요 ㅎㅎ

석진님이 테스트 작성에 어려움을 겪었던 부분에 대해 말씀해주시면, 좀 더 도움을 드릴 수 있을 것 같네요 :)

2024-01-13 12:23 UTC, shin-mallang commented on src/main/java/racingcar/domain/RacingCars.java
> +        final RacingCar maxPositionCar = findMaxPositionCar();
final이 붙었다 떼졌다 하네요!

2024-01-13 12:23 UTC, shin-mallang commented on src/main/java/racingcar/domain/RacingCars.java
> +    private List<String> findSamePositionCars(RacingCar maxPositionCar) {
메서드 순서가 사용 순서에 맞게 findMaxPositionCar()가 먼저 와야 읽기 좋지 않을까요?

2024-01-13 12:23 UTC, shin-mallang commented on src/main/java/racingcar/domain/RacingCars.java
> +    private RacingCar findMaxPositionCar() {
findWinner는 어떨까요?

2024-01-13 12:23 UTC, shin-mallang commented on src/main/java/racingcar/domain/generator/RandomNumberGenerator.java
> +    @Override
공백

2024-01-13 12:23 UTC, shin-mallang commented on src/main/java/racingcar/domain/validator/CarNamesValidator.java
> +
전 여기 떼는걸 좋아합니다만, 석진님 코드를 보니 떼진곳도 있고 안뗴진 곳도 있네요.
통일 부탁드려요!

2024-01-13 12:23 UTC, shin-mallang commented on src/main/java/racingcar/domain/validator/CarNamesValidator.java
> +
의미없는 공백 같아요!

2024-01-13 12:23 UTC, shin-mallang commented on src/main/java/racingcar/domain/validator/CarNamesValidator.java
> +        String[] cars = names.split(",");
마찬가지로 ,은 도메인에서 신경써야할게 맞을까요?

2024-01-13 12:23 UTC, shin-mallang commented on src/main/java/racingcar/domain/validator/TryCountValidator.java
> +        }
굳이 분리하지 않고 ParseInt로만 처리하는게 더 깔끔하고 쉽지 않을까요?

2024-01-13 12:23 UTC, shin-mallang commented on src/main/java/racingcar/domain/validator/TryCountValidator.java
> +    public static boolean isInteger(String tryCount) {
공백

2024-01-13 12:23 UTC, shin-mallang commented on src/test/java/InputViewTest.java
> +        String names = "";
공백이 여러개면 성공하나요? 실패하나요?

2024-01-13 12:23 UTC, shin-mallang commented on src/test/java/InputViewTest.java
> +    @DisplayName("tryCount가 공백이 경우 테스트")
NullAndEmptySource라는 것도 있답니다

2024-01-13 12:23 UTC, shin-mallang commented on src/test/java/InputViewTest.java
> +    @DisplayName("올바르지 않은 형식의 tryCount를 넣었을 때의 테스트")
올바른 것에 대한 테스트는 없나요?

2024-01-13 12:23 UTC, shin-mallang commented on src/test/java/InputViewTest.java
> +        assertThat(emptyNameException.getMessage()).isEqualTo("하나의 자동차라도 입력해주세요.");
체이닝 시키는 법은 없을까요?

2024-01-13 12:23 UTC, shin-mallang commented on src/test/java/RacingCarTest.java
> +        final NumberGenerator numberGenerator = new MovableNumberGenerator();
5일때 성공한다는 보장은 어디있나요?

2024-01-13 12:23 UTC, shin-mallang commented on src/test/java/RacingCarTest.java
> +        final NumberGenerator numberGenerator = new NonMovableNumberGenerator();
1일때는 실패하나요? 정말요?

2024-01-13 12:23 UTC, shin-mallang commented on src/test/java/RacingCarTest.java
> +
공백 두칸

2024-01-13 13:39 UTC, hsjni0110 commented on src/main/java/racingcar/controller/RacingGame.java
> +    private int tries;
상태가 변경될 수도 있겠네요..! final을 붙여 변경 불가능으로 만들겠습니다!

2024-01-13 13:53 UTC, hsjni0110 commented on src/main/java/racingcar/domain/RacingCars.java
> +        racingCars.forEach(racingCar -> Bars.append(racingCar.getCurrentBarStatus()).append("\n"));
SRP에 위반되는 것 같습니다..! 말씀하신대로 출력 로직은 따로 분리하는 것이 맞는 것 같습니다.

궁금한 점이 있습니다! 이전에 공부면서 getter를 사용하지 말고, 객체에 메세지를 전달하라는 글을 보았습니다.

처음에는 출력 로직을 View에 전부 구현하려 하다가 car와 cars의 프로퍼티에 접근해야하는 이유로 getter를 안사용할 수가 없더군요..

그렇다고, 글에서 본 것처럼 getter를 사용하지 않으려하니 클래스에 너무 많은 책임이 주어지는 것 같아 객체 지향적이지 못한 코드이기도 한 것 같습니다.

이러한 상황에서는 어떤 선택이 더 나은 선택일까요..?🤔

2024-01-13 14:29 UTC, hsjni0110 commented on src/main/java/racingcar/domain/validator/CarNamesValidator.java
> +        String[] cars = names.split(",");
제 코드에서 CarNameValidator는 자동차 이름에 대한 검증 클래스로써 사용합니다..!

다만, names를 String[]로 가져오려고 view에서 split한 후에 가져오면 공백 관련 검증이 조금 난잡해지는 것 같습니다..ㅜㅜ(NULL 체크 같은 것도 배열로 가져오면 처리하기가 힘든 것 같습니다...) 좋은 방법이 있을까요..?

아, 그리고 검증 클래스 이외의 cars같은 클래스에서는 split로직은 전부 view로 가져왔습니다..!

2024-01-13 15:23 UTC, awj1052 commented
전체적인 흐름이나 validator 부분에서 많은 것을 배워갑니다!!

2024-01-13 15:25 UTC, awj1052 commented on src/test/java/RacingCarsTest.java
> +        String carNames = "소나타,마티즈,싼타페";
BeforeEach로 테스트 픽스처를 만드는 것도 좋을 것 같습니다!

2024-01-14 07:22 UTC, hsjni0110 commented on src/test/java/RacingCarsTest.java
> +        String carNames = "소나타,마티즈,싼타페";
setUp 코드 만들었습니다 감사합니다..! :)

2024-01-14 08:19 UTC, shin-mallang commented on src/main/java/racingcar/controller/RacingGame.java
> +    private int tries;
맞습니다:)
추가적으로 이번 미션에서는 고려할 필요는 없지만, 생각해 보시면 좋을 것 같아 한가지 상황을 생각해 보사면 좋겠어요!

만약 여러 명의 사용자가 동시에 자동차 게임을 사용할 수 있도록 만드는 경우, 위 코드가 가지는 문제점은 무엇일까요?😯

2024-01-14 08:25 UTC, shin-mallang commented on src/main/java/racingcar/domain/RacingCars.java
> +        racingCars.forEach(racingCar -> Bars.append(racingCar.getCurrentBarStatus()).append("\n"));
SRP도 위반되는 것도 맞습니다 :) 
가장 큰 문제점은 뷰의 요구사항이 바뀌는 경우, 뷰가 바뀌어야 하는데 도메인에서 변경이 발생한다는 점이지요.

> 궁금한 점이 있습니다! 이전에 공부면서 getter를 사용하지 말고, 객체에 메세지를 전달하라는 글을 보았습니다.
처음에는 출력 로직을 View에 전부 구현하려 하다가 car와 cars의 프로퍼티에 접근해야하는 이유로 getter를 안사용할 수가 없더군요..

객체에 메세지를 전달하라는 그 의미를 잘 생각해 보시면 될 것 같아요.
getter를 마구잡이로 사용하게 되면, 객체가 자신의 책임을 다 하지 못할 가능성이 있기에 getter의 사용을 금지했던 것입니다.

객체가 가진 정보를 출력하는 것이 목적이라면, 그 목적에 따라 사용되는 getter는 문제가 없는 것이죠 ㅎㅎ

요구사항을 통해 금지를 하라 했지만, 정말 모든 경유에서 사용하지 말라는 의미는 아니었습니다 ㅎㅎ

이제 그럼 해당 부분은 getter를 사용해서 한번 바꿔보시고, 다시 말씀해주세요!

2024-01-14 08:36 UTC, hsjni0110 commented on src/main/java/racingcar/controller/RacingGame.java
> +    private int tries;
제 생각으론, 아무래도 같은 자원을 사용하다 보니 동시성 이슈가 발생할 거 같다는 느낌이 듭니다.. 동기화를 고려해보아야 할 거 같습니다..!

2024-01-16 05:32 UTC, hsjni0110 commented on src/main/java/racingcar/controller/RacingGame.java
> +    private int tries;
생각해보니 static을 붙이지 않으면 동시성 문제가 일어날 일이 없네요..! 하지만, 매번 변수가 할당되어야 해서 성능이 좋지 않을 것 같다는 생각이 듭니다!

2024-01-16 10:09 UTC, shin-mallang requested changes

2024-01-18 14:54 UTC, hsjni0110 commented on src/main/java/racingcar/domain/validator/CarNamesValidator.java
> +        String[] cars = names.split(",");
반영완료 하였습니다..!

2024-01-18 15:10 UTC, merged