[2단계] 안우진 미션 제출합니다.
CNU-SPICY/java-racingcar pull request #11
Opened 2024-01-12 18:43 UTC by awj1052

push가 이상하게 되어서 revert 좀 했습니다..

MVC 지식이 하나도 없어 다른 사람 코드를 많이 참고하게 되는 것 같습니다.

2024-01-13 11:41 UTC, hsjni0110 reviewed
[페어리뷰] 리팩토링 관련해서 리뷰남기고 갑니다! 😀

2024-01-13 11:41 UTC, hsjni0110 commented on src/test/java/racingcar/domain/RandomGeneratorTest.java
> +        RandomGenerator randomGenerator = new RandomGenerator(() -> arg);
난수를 테스트 하기 위해서 콜백함수로 값 자체를 리턴하도록 하셨네요..! 제가 생각하기론, RandomUtil이라는 인터페이스를 만들었으니, 4이상의 값을 리턴하는 구현체와 4보다 작은 값을 리턴하는 구현체를 만들어보는 것도 괜찮을 거 같아요!

2024-01-13 12:38 UTC, shin-mallang requested changes
안녕하세요 우진님~~~
2단계 미션 고생 많으셨습니다!
커밋 내용이 날라가서 어떤 식으로 작성했는지는 볼 수 없지만,
전체적으로 기능 분리도 잘 되었고, 코드가 많이 좋아졌네요 💯 

간단하게 리뷰 남겼으니 확인 부탁드려요!

궁금한게 있으시면 댓글로 달아주시거나, 따로 카톡 주셔도 돼요!

2024-01-13 12:38 UTC, shin-mallang commented on src/main/java/racingcar/domain/Car.java
> +    private static final int MOVEMENT_CONDITION = 4;
도메인 로직을 도메인에 반영 잘 해주셨어요! 💯

2024-01-13 12:38 UTC, shin-mallang commented on src/main/java/racingcar/domain/Car.java
> +    private static final int RANDOM_RANGE = 10;
랜덤의 범위에 대해 Car가 알아야 하는게 맞을까요?

2024-01-13 12:38 UTC, shin-mallang commented on src/main/java/racingcar/domain/Car.java
> +            }).generate());
람다식을 활용하신 모습 보기 좋습니다 💯 
그런데 이렇게 내부에서 RandomGenerator를 생성해서 사용하면 테스트하기 힘들지 않을까요?
어떤 식으로 변경하면 해당 메서드를 테스트하기 편해질까요?

2024-01-13 12:38 UTC, shin-mallang commented on src/main/java/racingcar/domain/Cars.java
> +public class Cars {
Cars의 로직이 모두 static하게 작성되었네요!
어떠한 이유가 있을까요??

(한가지 팁을 드리자면 도메인 로직은 최대한 static하지 않게 작성해보려는 연습을 하시면 좋을 것 같아요!)

2024-01-13 12:38 UTC, shin-mallang commented on src/main/java/racingcar/domain/RandomGenerator.java
> +    RandomUtil randomUtil;
인터페이스 구현체에서 또다시 인터페이스를 필드로 가지도록 구현할 필요가 있을까요?

2024-01-13 12:38 UTC, shin-mallang commented on src/main/java/racingcar/view/InputView.java
> +        System.out.println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).");
@hsjni0110 
석진님도 같이 보시면 좋을 것 같아서 말씀드려요!

석진님 의견도 좋을 말씀이고, 이런 식으로 작성하는 분들도 매우 많습니다.
그런데 저는 개인적으로 이러한 부분에서는 굳이 상수로 추출하지 않는 편입니다.

상수로 추출하면 뷰에 어떤 식으로 출력될지 확인하는데 위에 갔다 아래 갔다 하느라 시간이 걸리고, 한눈에 파악하기도 힘들기 때문이죠.
비슷한 예시로 예외 메세지 등도 있을 것 같네요.

변하지 않는다고 해서 무조건 상수로 추출하기보단, 가독성에 대해서도 한번씩은 생각해주시고 코드를 작성해 보셔도 좋을 것 같아요!

(물론 석진님 방법이 보기 더 좋다 하시는 분들도 있을테니, 이는 개인별, 혹은 팀별로 상의 후 정하면 좋겠죠?)

2024-01-13 12:38 UTC, shin-mallang commented on src/test/java/racingcar/domain/CarTest.java
> +    @ParameterizedTest
ParameterizedTest 에 대해 학습하고 이를 사용해주셨네요 💯 💯 💯

2024-01-13 12:38 UTC, shin-mallang commented on src/test/java/racingcar/domain/CarTest.java
> +
공백 신경써주세요

2024-01-13 12:38 UTC, shin-mallang commented on src/test/java/racingcar/domain/CarTest.java
> +    @DisplayName("move(arg) 테스트")
단순히 Move 테스트하고만 하기보다는, 정확히 Move를 통해 어떤 동작을 하는 것을 테스트하는지를 구체적으로 명시해주면 좋을 것 같아요!

2024-01-13 12:38 UTC, shin-mallang commented on src/test/java/racingcar/domain/CarTest.java
> +    @DisplayName("isSamePosition() 테스트")
마찬가지로 무엇을 테스트하는지 명확하게!! 
나머지 테스트들도 동일합니다 :)

2024-01-13 12:38 UTC, shin-mallang commented on src/test/java/racingcar/domain/CarsTest.java
> +
없다면 비워두셔도 돼요!

2024-01-13 12:38 UTC, shin-mallang commented on src/test/java/racingcar/domain/CarsTest.java
> +        assertThat(result).contains("pobi", "crong", "honux");
contains 사용 💯 💯 💯 
```java
assertThat(Cars.getCars())
    .extraction(Car::getName)
    .contains("pobi", "crong", "honux"); 
```
와 같이도 작성할 수 있답니다 :)

2024-01-13 15:00 UTC, awj1052 commented on src/main/java/racingcar/controller/RacingController.java
> +    public void setNames(final String carNames){
initCarByNames 으로 변경했다가 해당 메소드 역할을 생성자로 넘겨줬습니다! 감사합니다.

2024-01-13 15:02 UTC, awj1052 commented on src/test/java/racingcar/domain/RandomGeneratorTest.java
> +        RandomGenerator randomGenerator = new RandomGenerator(() -> arg);
0~3까지만 반환하는 것과 4~9까지 반환하는 RandomGenerate 객체를 사용하도록 변경했었습니다.
이후, 난수 생성 방식을 변경하면서 아쉽지만 해당 부분을 삭제했습니다. 감사합니다!

2024-01-13 15:05 UTC, awj1052 commented on src/main/java/racingcar/domain/Car.java
> +            }).generate());
RandomUtil 인터페이스의 존재가 의미 없는 것 같아 삭제하고,
RandomGenerate 객체는 난수만 생성하는 역할을 부여했습니다.
난수의 범위 역시 위 객체가 알고 있는 것이 맞다고 생각합니다.

2024-01-13 15:06 UTC, awj1052 commented on src/main/java/racingcar/domain/Cars.java
> +public class Cars {
첫 단추를 잘못 꿰어서 이렇게 된 것 같습니다.
static하지 않도록 변경했습니다!

2024-01-13 15:07 UTC, awj1052 commented on src/test/java/racingcar/domain/CarTest.java
> +
코드 작성 이후 공백 검수를 한 번 더 진행하는 식으로 해야겠습니다!!

2024-01-13 15:08 UTC, awj1052 commented on src/test/java/racingcar/domain/CarTest.java
> +    @DisplayName("move(arg) 테스트")
테스트 DisplayName을 보다 명확하게 수정했습니다.

2024-01-13 15:08 UTC, awj1052 commented on src/test/java/racingcar/domain/CarsTest.java
> +        assertThat(result).contains("pobi", "crong", "honux");
꿀팁 감사합니다 ㅎㅎㅎ

2024-01-13 15:21 UTC, awj1052 commented
Test Comment

2024-01-16 10:44 UTC, hsjni0110 reviewed
추가적으로 궁금한 점이나 리뷰 남겼습니다!

2024-01-16 10:44 UTC, hsjni0110 commented on src/main/java/racingcar/domain/Cars.java
> +                .collect(Collectors.toUnmodifiableList());
리스트의 수정 금지를 위해서 toUnmodifeableList()를 사용하셨네요! final은 불완전한 불변성을 가진다고 알고 있는데, 이걸 쓰면 완전히 불변성이 되나요?

2024-01-16 10:44 UTC, hsjni0110 commented on src/main/java/racingcar/view/InputView.java
> +        return carNames;
입력한 값에 대한 validation 코드도 있었으면 좋겠다는 생각이 듭니다! 테스트 코드도 있으면 더 좋고요..!

2024-01-16 10:44 UTC, hsjni0110 commented on src/main/java/racingcar/domain/Cars.java
> +public class Cars {
개인적으로 궁금한 건데, **static**을 쓰면 어떤 점이 안 좋을까요?

제가 아는 선에서는

1. 메모리 낭비(미리 할당 받기 때문)

2. 디버깅/테스트 힘듬

3. controller 단에서는 사용할 경우, 동시성 문제 발생 가능

이 정도 인 것 같은데 그 외에 더 사용하지 말아야 할 이유가 있을까요?🤔(혹은 어쩔 수 없이 써야하는 경우라던가...)

2024-01-16 10:44 UTC, hsjni0110 commented on src/main/java/racingcar/view/OutputView.java
> +            String statusOfCar = car.getName() +
문자열이 자주 연결 되는 경우에는 String 보단, StringBuilder가 낫다고 알고 있습니당. 이번 과제의 경우 크게 다르진 않겠지만, 혹시 문자열을 자주 더하는 과정이 있다면 StringBuilder가 좋은 것 같아요!

2024-01-16 11:39 UTC, awj1052 commented on src/main/java/racingcar/domain/Cars.java
> +                .collect(Collectors.toUnmodifiableList());
원본 객체와의 참조는 끊기지 않는다네요.
set(), add(), remove() 메소드 호출 시 RuntimeException이 발생하긴 합니다.

2024-01-16 12:28 UTC, awj1052 commented on src/main/java/racingcar/view/OutputView.java
> +            String statusOfCar = car.getName() +
확실히 문자열을 합칠 때 String 보다 StringBuilder 가 시간, 공간복잡도에 대해 좋다고 알고 있습니다.

방금 궁금해서 실행 시간 측정해봤습니다.
length가 50,000 인 문자열을 선언할 때 다음 3가지로 나누어 진행했습니다.
1) String a = "1" + "1" + "1" + ... + "1";
2) String a = ""; for(int i=0; i<50000; i++) a += "1";
3) StringBuilder 객체와 append 메소드 사용

결과는 다음과 같이 나왔습니다.
1) 약 0ms
2) 약 2200ms
3) 약 5ms 

1번 케이스는 사실 드문 경우이기 때문에 문자열을 다룰 때는 StringBuilder를 사용해야겠습니다!

2024-01-16 12:30 UTC, hsjni0110 commented on src/main/java/racingcar/view/OutputView.java
> +            String statusOfCar = car.getName() +
오 테스트는 안해봤는데, 차이가 꽤 많이 나네요..! 좋습니당

2024-01-16 14:30 UTC, awj1052 commented on src/main/java/racingcar/view/InputView.java
> +        return carNames;
방금 반영했습니다!

2024-01-18 15:13 UTC, shin-mallang commented on src/main/java/racingcar/domain/Cars.java
> +public class Cars {
static을 사용하게 되면 객체지향스럽지 못하게 되죠..!
객체는 상태와 행위를 갖지만, static 한 것은 상태를 갖는다기에는 모든 객체에서 동일한 상태를 갖게 되니까요?
static이 무조건 나쁘다는 건 아닙니다.
저도 utility성 클래스에는 static을 자주 사용합니다.
단지 Cars가 과연 static하게 작성되는게 좋을까? 고민해 보았을 때는, 좋지 않다고 생각했던 것이죠

2024-01-18 15:20 UTC, shin-mallang commented on src/main/java/racingcar/view/OutputView.java
> +            String statusOfCar = car.getName() +
@awj1052  @hsjni0110  좋은 토론이네요..
문자열 더하기 사용 시 바이트코드를 살펴보면 자바가 어느정도 최적화를 해주는 것을 볼 수 있습니다.
`StringConcatFactory`라는 키워드로 검색해도 몇가지 자료가 나오긴 할거고요..
한번쯤 보면 재밌습니다..ㅎㅎ

2024-01-18 15:20 UTC, merged