[2단계] 김현서 미션 제출합니다.
CNU-SPICY/java-racingcar pull request #12
Opened 2024-01-13 03:20 UTC by sans29374

getter/setter 없이 어떻게 코드를 짜야할 지 고민을 많이 해야할 것 같습니다. 또한 코드를 짜다보면 mvc의 세가지 요소의 기능의 구분이 모호해질 때가 있어서 이 부분에 대해서도 더 공부해야할 것 같습니다.

2024-01-13 12:48 UTC, shin-mallang requested changes
안녕하세요 현서님!
2단계 미션 고생 많으셨습니다!
MVC 구조가 처음이실 텐데 너무 잘 리팩토링 해주셨네요 💯 

리뷰 간단히 남겼으니 확인 부탁드리고, 혹시 물어보고 싶은게 있다면 댓글로 달아주시거나, 카톡방에 올려주시거나, 저에게 따로 카톡 주시면 됩니다!

2024-01-13 12:48 UTC, shin-mallang commented on src/main/java/racingcar/controller/RacingGameController.java
> +    }
너무 깔끔하네요 💯

2024-01-13 12:48 UTC, shin-mallang commented on src/main/java/racingcar/domain/Car.java
>  public class Car {
달 곳이 없어서 여기에 달게요!
4와 같은 매직 넘버는 의미있는 상수로 분리해보는것은 어떨까요?

2024-01-13 12:48 UTC, shin-mallang commented on src/main/java/racingcar/domain/Car.java
> +        return name + " : " + "-".repeat(distance);
Car는 도메인인데, 이는 View 로직 같아요!
도메인이 뷰에 의존하면 어떤 부분에서 문제가 발생할까요?

2024-01-13 12:48 UTC, shin-mallang commented on src/main/java/racingcar/domain/RacingGame.java
> +        cars = new ArrayList<>();
```java
private List<Car> cars = new ArrayList<>();
```
를 해주면 더 깔끔하지 않을까요?

2024-01-13 12:48 UTC, shin-mallang commented on src/main/java/racingcar/domain/RacingGame.java
> +        IntStream.range(0, tryCount)
Stream 사용 💯 

그런데 여기서는 Stream보다는 for문이 가독성이 더 좋을 것 같은데, 어떻게 생각하시나요?

2024-01-13 12:48 UTC, shin-mallang commented on src/main/java/racingcar/domain/RacingGame.java
> +                    OutputView.printCurrentStatus(generateStatus()); // 각 회차별 상태 출력
도메인에서 View를 의존하고 있네요!
이러면 어떤 문제가 발생할까요?
그리고 이런 상황을 어떻게 해결할 수 있을까요?

2024-01-13 12:48 UTC, shin-mallang commented on src/main/java/racingcar/domain/RacingGame.java
> +    //현재 상태 반환
의미없는 주석 같아요

2024-01-13 12:48 UTC, shin-mallang commented on src/test/java/carTest.java
> +        assertEquals(initialDistance + 1, car.getDistance());
어쩔때는 실패하고 어쩔때는 성공하는 테스트네요!

2024-01-13 12:48 UTC, shin-mallang commented on src/main/java/racingcar/domain/Car.java
>  public class Car {
추가로 move() 메서드가 이런 식으로 내부에서 랜덤값을 활용하게 되면 테스트가 불가능해져요!
확인해보니 작성된 테스트가 정말 랜덤하게 성공하거나 실패하고 있고요!
이러한 문제를 어떻게 해결할 수 있을까요?

2024-01-13 14:57 UTC, Sunkist18 reviewed
### 좋아 보이는 점 👍 
- MVC 아키텍처 적용으로 책임과 역할이 더욱 명확해진 것 같아요!
- Car 클래스에서 name과 distance 필드가 private로 설정되서 캡슐화가 강화된 것 같아요!
- 코드 중복이 줄어들어서 가독성과 유지보수성이 향상된 것 같아요!
- 입출력이 메인 어플리케이션 로직에서 분리됨에 따라, 코드의 가독성이 오르고, 유지보수에 유연성이 증가 한 것 같아요!

### 더 생각해보면 좋아보이는 사항 💭 
- 사용자 입력 및 기타 작업에서 발생할 수 있는 예외 사항에 대한 처리를 해봐도 좋을 것 같아요!
- 코드 내에서 직접적으로 숫자를 사용하는 '매직 넘버(magic number)'가 보여요! 명확한 이름의 상수로 대체해봐도 좋을 것 같아요!


### 그 외로 말씀드리고 싶은 점
자세한 내용들은 코드에 따로 주석을 달아두었습니다! 확인해보세요...!
뒤에 이모지😄를 달면 말이 좀 더 부드러워 보인다고 해서 리뷰에 적용해봤는데 어떠실지 모르겠네요

2024-01-13 14:57 UTC, Sunkist18 commented on src/test/java/RacingGameTest.java
> +            assertTrue(status.matches("(Car1|Car2) : -+"));
setUp()에서 carNames를 Car1과 Car2로 정의한 뒤, 이를 테스트에서 사용하고 있네요
그런데 Car1과 Car2 말고 다른 자동차의 이름을 사용하거나, 여러 자동차를 추가해서 사용해야하는 경우가 발생한다면 어떨까요?

이러한 경우는 이 테스트를 재사용 할 수 없게 만드는 경우가 될 수 있답니다 🤔 
테스트의 유용성을 제한하는 방식인 것 같습니다!

2024-01-13 14:57 UTC, Sunkist18 commented on src/test/java/RacingGameTest.java
> +        assertFalse(winners.contains("Car2"));
이 테스트는 "Car1"이 항상 승자 중 하나가 되고 "Car2"는 항상 질 것이라고 가정하네요

그런데 move() 메서드 자체가 무작위성에 의존하기 때문에 테스트가 정상적으로 작동한다는 보장이 없습니다.
Random을 mock하는 방법에 대해 고민해봐야겠네요 😄

2024-01-13 14:57 UTC, Sunkist18 commented on src/test/java/carTest.java
> +        assertEquals(initialDistance + 1, car.getDistance());
이 테스트는 자동차가 항상 1만큼 전진한다고 가정하네요

그런데 move() 메서드 자체가 무작위성에 의존하기 때문에 테스트가 정상적으로 작동한다는 보장이 없습니다.
Random을 mock하는 방법에 대해 고민해봐야겠네요 😄

2024-01-13 14:57 UTC, Sunkist18 commented on src/test/java/carTest.java
> +        assertTrue(status.matches("TestCar : -+"));
setUp()에서 carName를 TestCar로 정의한 뒤, 이를 테스트에서 사용하고 있네요
그런데 TestCar 말고 다른 자동차의 이름을 사용하거나, 여러 자동차를 추가해서 사용해야하는 경우가 발생한다면 어떨까요?

이러한 경우는 이 테스트를 재사용 할 수 없게 만드는 경우가 될 수 있답니다 🤔
테스트의 유용성을 제한하는 방식인 것 같습니다!

2024-01-13 14:57 UTC, Sunkist18 commented on src/main/java/racingcar/view/InputView.java
> +        return scanner.nextInt();
getTryCount()는 Scanner.nextInt()를 사용하는데, 이는 입력 버퍼에 개행 문자를 남길 수 있습니다. 
이후의 읽기 작업에 영향을 줄 수 있으므로, nextLine()을 사용하고 정수를 직접 파싱하는 것은 어떨까요? 🤔

2024-01-13 14:57 UTC, Sunkist18 commented on src/main/java/racingcar/domain/RacingGame.java
> +                    OutputView.printCurrentStatus(generateStatus()); // 각 회차별 상태 출력
race() 메서드는 실행될 때마다, 상태를 출력하네요

이는 도메인 로직과 출력 로직을 결합한 것으로
컨트롤러나 다른 서비스에서 정보를 표시하도록 처리해서 관심사를 분리해보는건 어떨까요? 🤔

2024-01-13 14:57 UTC, Sunkist18 commented on src/main/java/racingcar/domain/Car.java
>  public class Car {
move() 메서드가 외부에서 제어할 수 없는 무작위성을 사용하네요
테스트하기 힘들어 질 수 있겠네요

2024-01-16 05:23 UTC, sans29374 commented on src/main/java/racingcar/domain/Car.java
> +        return name + " : " + "-".repeat(distance);
나중에 도메인이나 뷰를 변경할 때 다른 한 쪽이 영향을 받는 경우가 생길 것 같습니다. 그리고 도메인이나 뷰가 섞여있다면 가독성도 떨어질 것 같아요. 그래서 이 메서드를 삭제하고, OutputView 클래스에서 이 로직을 처리하도록 변경하였습니다. 감사합니다!

2024-01-16 05:23 UTC, sans29374 commented on src/main/java/racingcar/domain/Car.java
>  public class Car {
넵 해당 매직 넘버는 상수로 분리하였습니다!
저는 민우님의 코드를 참조하여, domain에 난수를 생성하는 클래스를 하나 만들어 move 메서드가 난수를 생성하는 외부 클래스에 의존하도록 작성하였습니다. 테스트를 할 때도 난수 생성 클래스를 통해 모의 객체를 만들어 테스트하도록 하였습니다.

2024-01-16 05:24 UTC, sans29374 commented on src/main/java/racingcar/domain/RacingGame.java
> +        cars = new ArrayList<>();
넵 더 깔끔한 것 같아요. 변경하였습니다 감사합니다!

2024-01-16 05:25 UTC, sans29374 commented on src/main/java/racingcar/domain/RacingGame.java
> +        IntStream.range(0, tryCount)
처음에는 단순히 라인을 적게 쓰려고 stream을 사용했는데, for문으로 하니 가독성이 더 좋아진 것 같아요. 감사합니다!

2024-01-16 05:33 UTC, sans29374 commented on src/main/java/racingcar/domain/RacingGame.java
> +                    OutputView.printCurrentStatus(generateStatus()); // 각 회차별 상태 출력
유연성이 떨어질 뿐만 아니라, 도메인의 정보가 바로 view로 나가버리게 된다면 도메인의 불필요한 정보도 필터없이 출력될 수도 있겠네요. 그래서 저는 race 메서드는 각 차들을 이동시키는 기능만 담당하도록 바꾸고, controller에서 tryCount만큼 race시킨 다음 출력에 필요한 정보만 outputView에 넘겨주도록 수정해보았습니다.

2024-01-16 05:33 UTC, sans29374 commented on src/main/java/racingcar/domain/RacingGame.java
> +    //현재 상태 반환
넵 삭제하였습니다 감사합니다!

2024-01-16 05:34 UTC, sans29374 commented on src/test/java/carTest.java
> +        assertEquals(initialDistance + 1, car.getDistance());
넵 RandomNumberGenerator를 통해 해당 문제를 고쳐보았습니다

2024-01-16 05:39 UTC, sans29374 commented on src/test/java/RacingGameTest.java
> +            assertTrue(status.matches("(Car1|Car2) : -+"));
아하 그렇군요, test를 재사용한다는 생각은 미처 하지 못했네요! 그렇다면 혹시 car객체의 이름과 개수를 무작위로 생성하는 메서드를 만드는 것도 하나의 방법이 될 수 있을까요...?? 🤔

2024-01-16 05:40 UTC, sans29374 commented on src/test/java/RacingGameTest.java
> +        assertFalse(winners.contains("Car2"));
넵 민우님 조언에 따라 랜덤으로 난수를 생성하는 클래스를 만들어서 모의 객체를 생성하는 테스트를 만들어보았습니다. 감사합니다!!

2024-01-16 05:41 UTC, sans29374 commented on src/test/java/carTest.java
> +        assertEquals(initialDistance + 1, car.getDistance());
넵 민우님 조언에 따라 랜덤으로 난수를 생성하는 클래스를 만들어서 모의 객체를 생성하는 테스트를 만들어보았습니다. 감사합니다!!

2024-01-16 05:43 UTC, sans29374 commented on src/main/java/racingcar/view/InputView.java
> +        return scanner.nextInt();
아..!! 넵 수정하였습니다 감사합니다!!

2024-01-16 05:43 UTC, sans29374 commented on src/main/java/racingcar/domain/RacingGame.java
> +                    OutputView.printCurrentStatus(generateStatus()); // 각 회차별 상태 출력
넵 민우님 조언에 따라 컨트롤러에서 race()에 따른 현재 상태 출력을 조율하도록 변경하였습니다. 감사합니다!!

2024-01-16 05:45 UTC, sans29374 commented on src/main/java/racingcar/domain/Car.java
>  public class Car {
넵 말씀해주신 조언에 따라 난수를 생성하는 RandomNumberGenerator 클래스를 작성해 테스트에 활용하였습니다. 감사합니다!!

2024-01-16 14:39 UTC, Sunkist18 commented on src/test/java/RacingGameTest.java
> +            assertTrue(status.matches("(Car1|Car2) : -+"));
좋은 방법이 될 것 같네요 👍

2024-01-18 15:21 UTC, merged