[2단계] 김보배 미션 제출합니다.
CNU-SPICY/java-racingcar pull request #13
Opened 2024-01-14 07:08 UTC by Kimbobae1

너무 늦게 올려 죄송합니다. 에러가 자꾸 나서..
테스트 코드는 아직 미작성입니다.

getter를 최대한 안 써보려고 했는데, 
view에서 출력을 위해 domain의 데이터(리스트)를 가져오는 경우와 승자를 찾기위해 car객체의 거리값을 비교하는 경우 getter 없이는 구현이 잘 안 되었습니다. 
방법을 좀 더 생각해보겠습니다.

MVC 패턴대로 리팩터링을 해보았는데 controller와 domain 사이의 기능을 어떻게 구분하고 나누어야 할지 고민이 많이 되었습니다.
domain은 데이터 관련 부분이니 car들을 저장하는 부분까지만 담당하고, controller가 racing기능(move, winner찾기)을 담당해 view와 domain을 연결해주고 전체적인 역할을 수행하는 것인지 / 
아니면 domain에 racing 기능을 하는 클래스가 있고, controller는 view와 domain 사이에서 view와 domain의 메서드를 실행하며 데이터를 넘겨주는 역할만 하는지 /
아니면 위의 두 경우 둘다 틀린지 고민을 했습니다..

또 사용자에게 입력을 받을 때 "경주할 자동차의 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분)" 와 같은 출력문은 입력받을 때 사용되니 InputView인지, 출력문이니 OutputView 인지도 궁금합니다.

처음해보는 내용이라 모르는 부분이 많았습니다.
일단 요구사항대로 view의 객체가 domain의 객체에 의존할 수는 있지만, controller에 의해 데이터를 받아야하고, domain의 객체는 view객체에 의존하지 않도록 구현해 보려고 했습니다.

2024-01-14 07:57 UTC, juntae6942 reviewed
MVC pattern 적용을 잘한 것 같아요! 다만 저처럼 불필요한 개행이나 정의가 있는 것 같아요.

2024-01-14 07:57 UTC, juntae6942 commented on src/main/java/racingcar/domain/Car.java
>          return distance;
불필요한 개행이 있는 것 같아요

2024-01-14 07:57 UTC, juntae6942 commented on src/main/java/racingcar/domain/Car.java
> +        if (random >= 4) {
바뀌지 않는 값이라면 상수로 빼는건 어떨까요?

2024-01-14 07:57 UTC, juntae6942 commented on src/main/java/racingcar/domain/RacingGame.java
> +    private ArrayList<String> winners = new ArrayList<>();
선언과 정의가 섞여 있는 것 같아요 생성자에 통일해서 정의하는 건 어떨까요?

2024-01-14 07:57 UTC, juntae6942 commented on src/main/java/racingcar/controller/RacingController.java
>          final int tryCount = inputView.getTryCount();
불필요한 개행인 것 같아요

2024-01-15 04:31 UTC, Kimbobae1 commented on src/main/java/racingcar/domain/Car.java
> +        if (random >= 4) {
오 좋아요 public static final int MOVABLE_NUMBER = 4; 이렇게 빼보겠습니다

2024-01-15 04:31 UTC, Kimbobae1 commented on src/main/java/racingcar/domain/RacingGame.java
> +    private ArrayList<String> winners = new ArrayList<>();
그렇네요, 정의 부분을 생성자로 옮기겠습니다

2024-01-15 04:35 UTC, Kimbobae1 commented on src/main/java/racingcar/controller/RacingController.java
>          final int tryCount = inputView.getTryCount();
불필요한 개행을 없애보겠습니다

2024-01-16 10:08 UTC, shin-mallang requested changes
안녕하세요 보배님!
리뷰가 너무 늦었네요...ㅠㅠ

MVC 구조 너무 잘 적용해 주셨습니다!
코드가 많이 깔끔해진 것 같아요!!

테스트도 처음이실 텐데 이런저런 테스트 학습 방법을 공부하시고 적용해보신 것 같아요 💯 

너무너무 잘 하셨고, 간단히 리뷰 남겼습니다!
확인 부탁드려요!

2024-01-16 10:08 UTC, shin-mallang commented on src/main/java/racingcar/controller/RacingController.java
> +        final String[] carNames = inputView.getCarNames();
final 사용은 일관적으로 해주세요 !
(붙일거면 다 붙이거나, 붙이지 않을거면 다 붙이지 않거나)

2024-01-16 10:08 UTC, shin-mallang commented on src/main/java/racingcar/controller/RacingController.java
> +    public void race() {
이 사이는 공백을 지켜주세요

2024-01-16 10:08 UTC, shin-mallang commented on src/main/java/racingcar/controller/RacingController.java
> +        outputView.printWinner(racingGame.getWinners());
findWinners() 의 return으로 winner를 반환하게 해보는 것은 어떨까요?

2024-01-16 10:08 UTC, shin-mallang commented on src/main/java/racingcar/domain/Car.java
> +    public static final int MOVABLE_NUMBER = 4;
💯

2024-01-16 10:08 UTC, shin-mallang commented on src/main/java/racingcar/domain/RacingGame.java
> +    private final Car[] cars;
자동차가 내부적으로 이름을 가지고 있는데, 이곳에서 중복으로 관리할 필요가 있을까요?

2024-01-16 10:08 UTC, shin-mallang commented on src/main/java/racingcar/domain/RacingGame.java
> +            addWinner(car, max);
해당 메서드만을 보고 어떤 식으로 행위가 이루어질지 알기 어려울 것 같아요!
좀 더 명확하게 바꿔볼까요?

2024-01-16 10:08 UTC, shin-mallang commented on src/main/java/racingcar/view/InputView.java
> +        this.sc = new Scanner(System.in);
굳이 분리한 이유가 있나요?

2024-01-16 10:08 UTC, shin-mallang commented on src/test/java/racingcar/domain/CarTest.java
> +    void move(int input, int expected) {
테스트명이 좀 더 명확했으면 좋겠습니다!

2024-01-16 10:08 UTC, shin-mallang commented on src/test/java/racingcar/domain/RacingGameTest.java
> +    void moveCars(int input, int expected) {
공백 신경써주세요!

파라미터라이즈드 테스트 활용 너무 좋습니다:)

2024-01-16 12:39 UTC, Kimbobae1 commented on src/main/java/racingcar/controller/RacingController.java
> +        final String[] carNames = inputView.getCarNames();
앗 그렇네요, InputView와 OutputView에도 final을 사용하도록 코드 수정하겠습니다!

2024-01-16 12:39 UTC, Kimbobae1 commented on src/main/java/racingcar/controller/RacingController.java
> +    public void race() {
넵, 공백 신경쓰겠습니다

2024-01-16 12:42 UTC, Kimbobae1 commented on src/main/java/racingcar/controller/RacingController.java
> +        outputView.printWinner(racingGame.getWinners());
오 그렇게 하면 getWinners 메서드가 없어도 되고, 코드가 간결해지겠네요, 감사합니다!

2024-01-16 12:45 UTC, Kimbobae1 commented on src/main/java/racingcar/domain/RacingGame.java
> +    private final Car[] cars;
앗 그렇네요ㅎㅎ 이제보니 해당 클래스에서도 전혀 사용되지 않네요 수정하겠습니다.

2024-01-16 12:50 UTC, Kimbobae1 commented on src/test/java/racingcar/domain/RacingGameTest.java
> +    void moveCars(int input, int expected) {
감사합니다, 공백 신경쓰겠습니다!

2024-01-16 13:01 UTC, Kimbobae1 commented on src/main/java/racingcar/view/InputView.java
> +        this.sc = new Scanner(System.in);
선언과 정의를 분리해야 하나..? 싶어서 분리했던 것 같은데 굳이 그럴 필요가 없어보이네요, 수정하겠습니다ㅎㅎ

2024-01-16 13:06 UTC, Kimbobae1 commented on src/test/java/racingcar/domain/CarTest.java
> +    void move(int input, int expected) {
조금 더 명확하게 수정해보았습니다..! 테스트명이나 메서드명 작성 요령은 더 공부해보겠습니다

2024-01-16 13:32 UTC, Kimbobae1 commented on src/main/java/racingcar/domain/RacingGame.java
> +            addWinner(car, max);
음 addWinner 메서드의 이름을 addToWinnersListIfMaxDistance 로 바꿔보았는데, 아무래도 이렇게 바꾸는건 아니겠죠..? ㅠㅠ 메서드의 행위가 명확하게 보이도록 메서드들의 구조를 바꾸는게 좋을까요? 😢

2024-01-18 15:22 UTC, merged