2차 리팩토링
CNU-SPICY/java-racingcar pull request #14
Opened 2024-01-14 15:14 UTC by Sunkist18

### 주요 변경 사항
1. RacingCarApplication.java:
    - main 메소드에서 MovementCondition, InputView, OutputView에 대해 DI를 도입했습니다 😄 
    - Game 생성은 생성자를 통하는 것이 아니라 정적 팩토리 메소드 (createGame)을 사용하도록 변경했습니다!

2. Game.java:
    - MovementCondition을 의존성으로 포함하도록 리팩토링 했습니다.
    - 사용자 입력 처리(getCarNamesFromUser, getNumberOfTrialsFromUser) 및 레이스 로직(runRaces, declareWinners)을 메소드로 추출하여 코드를 인지하고 유지보수 하기 쉽게 변경했습니다.
    - Cars 생성에 MovementCondition을 포함하도록 변경했습니다.

3. Car.java:

    - MovementCondition을 의존성으로 추가하고, 이는 move 메소드에서 이동 로직을 결정하는 데 이용합니다!

4. Cars.java:

    - 모든 Car 인스턴스에 적용하기 위해 MovementCondition을 받는 생성자로 수정했습니다!
    - 자동차 배열 초기화를 더 간결하게 하기 위해 Arrays.stream 사용해봤습니다 👍 

5. MovementCondition 인터페이스:

    - MovementCondition을 인터페이스로 변환하여 이동전략의 확장성 및 유연성을 제공했습니다!
    - 구현체로 RandomMovementCondition과 ForceMovementCondition을 추가했습니다.

6. InputView.java:
    
    - 더 나은 리소스 관리를 위해 정적 Scanner 인스턴스를 사용하는 방식으로 리팩토링하고, closeScanner 메소드 추가했습니다!

7. 테스트 클래스 (CarTest, CarsTest):

    - 랜덤이 아닌, 결정적인 테스팅을 위해 ForceMovementCondition을 사용하도록 조정해서 테스트했습니다

2024-01-15 02:21 UTC, shin-mallang requested changes
안녕하세요 민우님~
애당초 코드를 너무 잘 작성해 주셔서 리뷰할 부분이 크게 없었네요 💯
MVC 구조에 맞게 분리도 잘 된 것 같아요!!


몇가지 질문드리고 싶은게 있는데요!

1. validator는 왜 패키지 분리를 하셨나요?
validator에서 검증하고 있는 로직은 무엇에 대한 로직일까요??

2. validator를 사용한 이유가 궁금해요!
별도의 validator 없이 도메인 모델(Car, Cars) 만으로도 충분히 검증에 대한 부분은 수행할 수 있을 것 같은데, 따로 검증기를 두신 이유가 궁금합니다 :)

--- 

추가로 검증기의 성공 케이스에 대한 단위 테스트는 작성되지 않은 것 같아요~

2024-01-15 02:21 UTC, shin-mallang commented on src/main/java/racingcar/controller/Game.java
> +    public static Game createGame(MovementCondition movementCondition, InputView inputView, OutputView outputView) {
정적 팩터리 메서드를 사용한 이유가 있을까요?

2024-01-15 02:21 UTC, shin-mallang commented on src/main/java/racingcar/controller/Game.java
> +    }
input뷰에서 입력을 위한 출력과, 입력 받는 부분을 함께 수행해보는 것은 어떻게 생각하시나요?

2024-01-15 02:21 UTC, shin-mallang commented on src/main/java/racingcar/controller/Game.java
>      }
해당 메서드는 따로 분리하지 않아도 충분히 명확하다고 생각해요!

2024-01-15 02:21 UTC, shin-mallang commented on src/test/java/racingcar/CarTest.java
>      private final String carName = "car";
순서!

2024-01-15 09:32 UTC, Sunkist18 commented on src/test/java/racingcar/CarTest.java
>      private final String carName = "car";
확실히 상수를 가변 필드보다 먼저 선언하는게 일반적인 컨벤션을 맞춰서 가독성이랑 일관성을 높이겠네요 👍 

```java
public class CarTest {
    private final String carName = "car";
    private Car car;
}
```

저도 이런식으로 순서를 바꾸는 게 더 좋을 것 같다고 생각합니다 감사합니다 😄

2024-01-15 09:36 UTC, Sunkist18 commented on src/main/java/racingcar/controller/Game.java
>      }
`declareWinners` 메서드를 따로 분리한 설계는 다음과 같은 목적을 지니고 있습니다.

1. 별도의 메서드로 분리해서, 그 메서드의 이름이 수행하는 작업을 명확하게 설명하기 위해서
2. 해당 로직이 게임의 다른 부분에서도 사용될 가능성이 있다면, 이를 별도의 메서드로 분리하는 것이 재사용성을 높일 수 있어서.

그래서 메서드를 분리한 설계를 한건데, 말씀해주신대로
1. 코드가 충분히 간단하고 명확한 것 같다.
2. 특정 시나리오에서만 사용된다.

위와 같은 이유로 별도의 메서드로 분리할 필요가 없어 보이네요 👍

2024-01-15 09:42 UTC, Sunkist18 commented on src/main/java/racingcar/controller/Game.java
> +    }
> input뷰에서 입력을 위한 출력과, 입력 받는 부분을 함께 수행해보는 것은 어떻게 생각하시나요?


1. UI입장에서 일관성과 직관성이 증가하고
2. 입력 관련 출력 로직과 입력 로직을 같은 뷰에 두면 응집도가 증가하고
3. 유지보수도 용이해질 것 같아보입니다.

하지만 제가 하나의 뷰에 작성하지 않은 이유는 다음과 같습니다.
1. 출력과 입력을 처리하는 로직을 분리해서, 각각의 책임을 명확하게 유지하고자 함
2. 확장성과 유연성의 관점에서, 시스템이 확장되었을 때 (e.g 다양한 종류의 입력과 출력이 필요해진 경우), 각각을 적절히 관리할 수 있는 구조를 설계하고자 함.

하지만, 현재 애플리케이션의 경우에는 유저에게 명확한 지침을 출력하고 입력을 즉시 받는 것이 사용자 경험을 개선할 수 있는 좋은 방법이 될 것 같습니다. 고민해볼 것 같습니다 💭

2024-01-15 09:49 UTC, Sunkist18 commented on src/main/java/racingcar/controller/Game.java
> +    public static Game createGame(MovementCondition movementCondition, InputView inputView, OutputView outputView) {
> 정적 팩터리 메서드를 사용한 이유가 있을까요?

정적 팩터리 메서드의 다양한 장점에 대해서는 이미 알고 계실테니,  
주어진 레이싱카 게임 어플리케이션에서 얻을 수 있는 장점 위주로 말씀드리자면

1. `Game.createGame(movementCondition, inputView, outputView)` 메서드를 통해 게임 인스턴스를 생성하는 과정을 명확하게 설명합니다. `new Game()` 대신 이 메서드를 사용함으로써, 어떤 종류의 Game 객체가 생성되는지, 그리고 어떤 종속성이 필요한지 명확히 이해할 수 있습니다.
2. 현재 시스템에서는 아직 정적 팩터리 메서드의 모든 장점을 활용하지 않을 수도 있지만, 이 메서드는 추후 시스템이 확장될 때 유연성을 제공하고자 했습니다. 나중에 다른 종류의 Game 인스턴스를 생성해야 할 경우(e.g. 다른 규칙이나 구성을 가진 게임), 같은 createGame 메서드를 오버로딩하거나 다른 이름의 정적 팩터리 메서드를 추가하여 쉽게 확장할 수 있도록 하였습니다.
3. single entry point을 제공함으로써, 인스턴스 생성 과정을 중앙화하고 통제할 수 있습니다. 이는 코드의 일관성을 높이고, 인스턴스 생성 로직을 한 곳에서 관리할 수 있습니다.

이러한 점들은 Game 클래스에 정적 팩터리 메서드를 사용함으로써 시스템이 얻는 구체적인 이점들입니다.   
이는 코드의 가독성, 유지보수성 그리고 확장성을 향상시키는 데 기여하며, 향후 시스템이 변화하거나 확장될 때 추가적인 유연성을 제공할 수 있습니다.

2024-01-15 10:45 UTC, sans29374 commented
안녕하세요 민우님!! 

MVC 구조가 명확하고 기능이 잘 구분되어 있어서, 코드를 읽으면서도 공부가 많이 되었습니다. 피드백보단 질문을 더 많이 드리게 되는 것 같네요...!! 자세한 리뷰는 코드에 달아놓겠습니다.

2024-01-15 10:49 UTC, Sunkist18 commented
> Member

@shin-mallang 님! 전체적인 꼼꼼한 리뷰 감사합니다 😄

Validator를 별도의 패키지로 분리한 이유는 주로 책임의 분리와 확장성을 고려한 설계 때문입니다. 

1. InputValidator는 오직 입력 데이터의 유효성 검사만을 담당합니다. 이를 통해 각 클래스와 모듈은 하나의 책임만을 가지고, 이는 유지보수와 확장성 측면에서 유리합니다.
2. 별도의 Validator 클래스를 두면, 다른 부분에서도 동일한 유효성 검증 로직을 재사용할 수 있습니다. 만약 다른 도메인에서도 자동차 이름의 길이나 형식이 동일한 경우, 기존의 Validator를 재사용할 수 있습니다.
3. 도메인 모델(Car, Cars)이 비즈니스 로직에 집중할 수 있습니다. 입력 유효성 검사 로직이 도메인 모델 내부에 위치하면, 모델이 UI 또는 외부 인터페이스에 의존적이게 될 수 있습니다. Validator를 분리함으로써, 도메인 모델은 순수하게 비즈니스 로직에만 집중할 수 있습니다.

2024-01-15 13:45 UTC, shin-mallang commented
@Sunkist18 답변 너무 감사합니다 민우님!
Mvc 개념 뿐만 아니라 객체지향에 대해서도 미이 많이 알고 계신 것 같아요! 💯 

답변 주신 내용을 바탕으로 새로운 시각을 드리기  위해 답변을 드릴게요(조금 따지듯이 들릴 수 있는데, 그런거 아니니 오해하지 말아주세요 😃 )

> Validator를 별도의 패키지로 분리한 이유는 주로 책임의 분리와 확장성을 고려한 설계 때문입니다.

> InputValidator는 오직 입력 데이터의 유효성 검사만을 담당합니다. 이를 통해 각 클래스와 모듈은 하나의 책임만을 가지고, 이는 유지보수와 확장성 측면에서 유리합니다.

> 별도의 Validator 클래스를 두면, 다른 부분에서도 동일한 유효성 검증 로직을 재사용할 수 있습니다. 만약 다른 도메인에서도 자동차 이름의 길이나 형식이 동일한 경우, 기존의 Validator를 재사용할 수 있습니다.

> 도메인 모델(Car, Cars)이 비즈니스 로직에 집중할 수 있습니다. 입력 유효성 검사 로직이 도메인 모델 내부에 위치하면, 모델이 UI 또는 외부 인터페이스에 의존적이게 될 수 있습니다. Validator를 분리함으로써, 도메인 모델은 순수하게 비즈니스 로직에만 집중할 수 있습니다.

답변 감사합니다!
민우님이 어떤 목적을 가지고 검증기를 사용하셨는지 잘 알 수 있었어요 :)

물론 지금 코드도 좋다고 생각하지만, 답변주신 내용에 더불에 몇가지 생각해 볼 만한 점을 말씀드릴게요!

> InputValidator는 오직 입력 데이터의 유효성 검사만을 담당합니다. 이를 통해 각 클래스와 모듈은 하나의 책임만을 가지고, 이는 유지보수와 확장성 측면에서 유리합니다.

제가 코드를 확인해 보니, '입력 데이터의 유효성' 이라는 부분에 자동차 이름이 5글자 이하인지, 경주에 참여하는 자동차 수가 5개 이하인지 등을 포함시켜 생각하시는 것 같아요!

그런데 자동차 이름을 6글자로 입력하면 '입력'이 유효하지 않은 것일까요?
저라면 입력은 유효하지만, 도메인 제약사항을 어긴다고 판단할 것 같아요!

하고 싶은 얘기는 현재의 검증기가 입력에 대한 유효성만을 검증하는 것이 아니라, 입력에 대한 유효성 + 도메인 로직에 대한 유효성을 검증하고 있는 것 같아요!

두 개의 다른 분야(뷰와 도메인)에 대한 검증 로직을 한곳에서 관리하다 보니, 뷰의 제약이 변경되든, 도메인의 제약이 변경되든 똑같이 검증기 코드가 변경되어야 하는 상황이 발생하게 됩니다.

이는 책임을 분리했으나, 너무 과도하게 분리하여 InputView와 Car의 책임이 검증기로 전가되었다는 생각이 들어요!
(응집도가 떨어졌다고 볼 수 있을 것 같아요)

검증기 없이도 Car랑 InputView만으로도 충분히 제 책임을 다 하며 검증을 수행할 수 있을 것 같고, 응집도의 관점에서는 검증기가 없는 편이 괜찮다는 생각이 드네요!


> 별도의 Validator 클래스를 두면, 다른 부분에서도 동일한 유효성 검증 로직을 재사용할 수 있습니다. 만약 다른 도메인에서도 자동차 이름의 길이나 형식이 동일한 경우, 기존의 Validator를 재사용할 수 있습니다.

이 부분에서도 몇가지 고려할 점이 있어요!
만약 다른 도메인에서 자동차 이름의 길이나 형식이 동일한 경우, 기존의 검증기를 재사용하는게 좋을까요?
저라면 다른 도메인이라면, 검증기도 따로 둘 것 같아요!(사실 검증기를 안 두고 그냥 도메인 모델 내에서 처리할 것 같지만요)
이유는 서로 다른 도메인은, 서로 다른 변경의 이유를 가지기 때문이에요.
도메인이 다른데 한 순간 같다고 해서 하나의 클래스로 모두 처리하게 되면, 해당 검증기는 이후 변경이 발생했을 때 너무 여러가지 이유로 변경되게 되고, 이는 단일 책임 원칙에 어긋난다고 볼 수 있을 것 같아요.
그로 인해 유지보수의 난이도는 극심해지겠죠(10개의 도메인에 대한 검증을 하나의 검증기에서 하는 상황을 생각해보면 많이 힘들겠죠)


> 도메인 모델(Car, Cars)이 비즈니스 로직에 집중할 수 있습니다. 입력 유효성 검사 로직이 도메인 모델 내부에 위치하면, 모델이 UI 또는 외부 인터페이스에 의존적이게 될 수 있습니다. Validator를 분리함으로써, 도메인 모델은 순수하게 비즈니스 로직에만 집중할 수 있습니다.

자동차 이름이 5글자 이하인 것은 Car에 대한 비즈니스 로직이고, 자동차 수가 5대 이하인 것은 Cars에 대한 비즈니스 로직이라 생각해요 :)

리뷰를 반영해서 한번 validator를 제거하고, 비지니스 제약(불변식이라고도 합니다)과 입력 검증을 각각 도메인 모델과 InputView에서 처리하도록 바꿔보시는 것은 어떨까요?

그러한 과정에서 새로운 시각을 얻어가실 수 있을 것 같아요!

2024-01-16 14:47 UTC, Sunkist18 commented
@shin-mallang 

InputValidator 에서 도메인의 책임을 가져가고 있다는 걸 놓치고 있었네요!
확실히 InputValidator를 계속 유지를 한다면 도메인의 검증은 최대한 배제하고, 정말 "입력"에 관한 검증만 수행하면 될 것 같네요
유효하게 입력된 값이 (e.g. readNumber) 실제 로직상에 맞는 값인지 (e.g. 라운드 수 > 0 )는 도메인에서 수행하는게 좋아보여요 👍

개인적으로 inputValidator에서 입력의 유효성하는 방식이 저는 좋아보여서, 
숫자 입력의 검증정도는 수행하도록 할 것 같기는 하네요! (나중에 다른 입력을 받을 수도 있기 때문)
다만, 말씀해주신 것처럼 응집도를 해치지 않기 위해 도메인에서 수행되어야 하는 검증은, 도메인에서 검증하게 수정해야할 것 같네요

꼼꼼한 리뷰 감사합니다 👍 👍 👍

2024-01-18 15:22 UTC, merged