MVC에 맞춘 refactorying
CNU-SPICY/java-racingcar pull request #9
Opened 2024-01-11 06:47 UTC by juntae6942

테스트 코드 아직 미작성

2024-01-13 11:52 UTC, shin-mallang requested changes
미션 고생하셨습니다~
리뷰는 처음부터 많이 달면 힘들 것 같아서 적당히 달았어요.

근데 그 전에 공백좀 신경써주세요 :)

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/controller/RaceController.java
> +    public RaceController() {
이런거 공백 신경써주세영

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/controller/RaceController.java
> +    private static InputView inputView;
static으로 설정한 이유가 뭘까요?

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/controller/RaceController.java
> +            Referee referee = new Referee(inputView.getInputCarName());
outputView를 굳이 사용하지 않고, inputView.getInputCarName() 에서 같이 화면에 출력해주는건 어떨까요?

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/controller/RaceController.java
> +
이런건 의미없는 공백같아 보이네여

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/controller/RaceController.java
> +            referee.move();
심판이 움직이나요?

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/domain/Car.java
> +    private final String carName;
순서

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/domain/Car.java
> +        moveCount++;
moveCount보다 더 좋은 변수명은 없을까여

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/domain/Car.java
> +    public static List<CarDto> makeCarDtos(List<Car> cars) {
domain에서 DTO에 의존하면 뭐가 좋고 뭐가 안 좋을까요?

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/domain/Car.java
> +    public int compareTo(Car car) {
compareTo를 재정의하면 문제는 없을까요?

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/domain/RandomGenerator.java
> +    }
굳이 왜 나눴죠?

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/domain/Referee.java
> +    }   // 자동차 이름을 이용한 생성자
불필요한 주석은 제거

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/domain/Referee.java
> +        cars = new ArrayList<>();
어떤건 생성자 외부에서 정의하고, 어떤건 생성자 내부에서 정의하네요. 
무슨 이유가 있나요?

2024-01-13 11:52 UTC, shin-mallang commented on src/main/java/racingcar/domain/Referee.java
> +    public void move() {
심판이 자동차를 움직여주는 표현이 좋을까요, 자동차가 움직이고 심판은 결과만 봐주는 게 좋을까요

2024-01-14 04:03 UTC, juntae6942 commented on src/main/java/racingcar/controller/RaceController.java
> +    public RaceController() {
신경 쓰겠습니다!

2024-01-14 04:04 UTC, juntae6942 commented on src/main/java/racingcar/controller/RaceController.java
> +    private static InputView inputView;
자동완성으로 넣어 버렸었네요 하하..;; final을 쓰려고 했던건데

2024-01-14 04:06 UTC, juntae6942 commented on src/main/java/racingcar/controller/RaceController.java
> +            Referee referee = new Referee(inputView.getInputCarName());
outputview와 inputview의 역할을 너무 나누려고 하다보니 불필요한 구현을 한 것 같습니다. 사실 고민했었거든요 출력한줄 하는건데 이걸 outputview에 나눠야 할지 말아야할지

2024-01-14 04:10 UTC, juntae6942 commented on src/main/java/racingcar/domain/Referee.java
> +    }   // 자동차 이름을 이용한 생성자
넵!!

2024-01-14 04:10 UTC, juntae6942 commented on src/main/java/racingcar/domain/RandomGenerator.java
> +    }
아직 모지리라 그렇습니다..ㅠㅠ

2024-01-14 04:11 UTC, juntae6942 commented on src/main/java/racingcar/controller/RaceController.java
> +            referee.move();
메서드 명 수정하겠습니다!!

2024-01-14 04:11 UTC, juntae6942 commented on src/main/java/racingcar/domain/Referee.java
> +        cars = new ArrayList<>();
이 또한 제가 모지리라...

2024-01-14 04:12 UTC, juntae6942 commented on src/main/java/racingcar/domain/Referee.java
> +    public void move() {
로직 수정해보겠습니다!!

2024-01-15 06:00 UTC, Kimbobae1 reviewed
[페어리뷰] MVC 패턴을 적용해서 너무 잘 작성하신 것 같아요. 궁금한 점과 함께 리뷰 남기고 갑니다!

2024-01-15 06:00 UTC, Kimbobae1 commented on src/main/java/racingcar/view/OutputView.java
> +    }
이 부분에서 시도 횟수 안내문은 자동차 이름을 입력받을 때와 다르게 OutputView에 작성하신 이유가 궁금합니다

2024-01-15 06:00 UTC, Kimbobae1 commented on src/main/java/racingcar/domain/Cars.java
> +    }
자동차의 전진 가능 여부를 판단하는 메서드와 인자에 따라 전진하는 메서드를 따로 분리했네요.
이렇게 하면 단위테스트를 하기 좋을 것 같아요! 😃

2024-01-15 06:00 UTC, Kimbobae1 commented on src/main/java/racingcar/domain/Cars.java
> +        return Car.makeCarDtos(winners);
저는 승리 자동차를 선정하는 방법이 어려웠는데 Collections을 사용해서 너무 잘 작성하신 것 같아요!

2024-01-15 06:00 UTC, Kimbobae1 commented on src/test/java/racingcar/domain/CarsTest.java
> +        cars.increaseMoveCount(true, car);
메서드를 잘 정의해서 mock없이도 전진 테스트를 할 수 있는 부분이 인상적이네요! 👍

2024-01-15 06:00 UTC, Kimbobae1 commented on src/main/java/racingcar/dto/CarDto.java
> +    }
저는 Dto로 따로 작성하신 부분들을 그냥 도메인의 car에 함께 작성하였는데, Dto 부분을 따로 작성하면 어떤 점이 좋은지 알고 싶습니다

2024-01-16 01:34 UTC, juntae6942 commented on src/main/java/racingcar/view/OutputView.java
> +    }
수정하다가 놓친 부분인 것 같네요! 수정했습니다.ㅎㅎ

2024-01-16 01:44 UTC, juntae6942 commented on src/main/java/racingcar/dto/CarDto.java
> +    }
DTO는 단순한 데이터 전달 객체로 사용하는 것이고, domain은 데이터를 보관하고 있는 model이라고 생각해서 객체로서의 존재를 model이 유지하고, DTO로만 데이터를 전달하여, getter와 setter의 사용을 지양하는 것이 정보은닉과, 비즈니스 로직에 대한 객체의 책임성을 지킬 수 있을 것 같아서 따로 DTO를 사용하여 데이터 전달을 했습니다.

2024-01-18 15:09 UTC, merged